# Generated by Django 2.2 on 2021-10-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='product_img',
            field=models.ImageField(null=True, upload_to='collection/static/img'),
        ),
    ]
