# Generated by Django 2.2 on 2021-10-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20211022_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='addedToCart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='men',
            name='product_img',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
