# Generated by Django 2.2 on 2021-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20211022_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
