# Generated by Django 2.2 on 2021-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_women'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=100)),
                ('product_img', models.ImageField(null=True, upload_to='collection/images')),
                ('addedToCart', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('latest', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
