# Generated by Django 2.2 on 2021-10-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi neque temporibus labore magni voluptate! Deleniti impedit maiores dolor sit corporis placeat perferendis, illum molestias mollitia deserunt nesciunt distinctio', max_length=1000),
        ),
    ]
