# Generated by Django 2.2 on 2021-10-22 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivered_on',
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 11, 2)),
        ),
    ]
