# Generated by Django 2.2 on 2021-10-22 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_auto_20211023_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered_on',
            field=models.DateField(default=datetime.date(2021, 11, 2)),
        ),
    ]
