# Generated by Django 2.2 on 2021-10-23 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_orders_delivered_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='accessory',
            name='deliverd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessory',
            name='delivered_on',
            field=models.DateField(default=datetime.date(2021, 11, 2)),
        ),
        migrations.AddField(
            model_name='accessory',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 11, 2)),
        ),
        migrations.AddField(
            model_name='accessory',
            name='mop',
            field=models.CharField(default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='accessory',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessory',
            name='ordered_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='accessory',
            name='quantity_ordered',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='men',
            name='deliverd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='men',
            name='delivered_on',
            field=models.DateField(default=datetime.date(2021, 11, 2)),
        ),
        migrations.AddField(
            model_name='men',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 11, 2)),
        ),
        migrations.AddField(
            model_name='men',
            name='mop',
            field=models.CharField(default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='men',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='men',
            name='ordered_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='men',
            name='quantity_ordered',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='women',
            name='deliverd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='women',
            name='delivered_on',
            field=models.DateField(default=datetime.date(2021, 11, 2)),
        ),
        migrations.AddField(
            model_name='women',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 11, 2)),
        ),
        migrations.AddField(
            model_name='women',
            name='mop',
            field=models.CharField(default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='women',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='women',
            name='ordered_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='women',
            name='quantity_ordered',
            field=models.IntegerField(default=1),
        ),
    ]
