# Generated by Django 2.2 on 2021-10-23 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_auto_20211023_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='delivered_on',
            field=models.DateField(default=datetime.date(2021, 10, 27)),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 10, 27)),
        ),
        migrations.AlterField(
            model_name='men',
            name='delivered_on',
            field=models.DateField(default=datetime.date(2021, 10, 27)),
        ),
        migrations.AlterField(
            model_name='men',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 10, 27)),
        ),
        migrations.AlterField(
            model_name='women',
            name='delivered_on',
            field=models.DateField(default=datetime.date(2021, 10, 27)),
        ),
        migrations.AlterField(
            model_name='women',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 10, 27)),
        ),
    ]
