# Generated by Django 3.2.8 on 2021-10-25 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_auto_20211024_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='delivered_on',
            field=models.DateField(default=datetime.date(2021, 11, 4)),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 11, 4)),
        ),
        migrations.AlterField(
            model_name='men',
            name='delivered_on',
            field=models.DateField(default=datetime.date(2021, 11, 4)),
        ),
        migrations.AlterField(
            model_name='men',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 11, 4)),
        ),
        migrations.AlterField(
            model_name='women',
            name='delivered_on',
            field=models.DateField(default=datetime.date(2021, 11, 4)),
        ),
        migrations.AlterField(
            model_name='women',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 11, 4)),
        ),
    ]
